version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: coral-postgres
    environment:
      POSTGRES_USER: coral_user
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: coral_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U coral_user -d coral_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
